site_name: Mobil Yaka Kılavuzu
site_url: https://example.com/
nav:
    - Home: index.md
    - Haberler: ./haberler/haberler.md
    - Tebrikler:
      - Tebrikler: ./tebrikler/tebrikler.md
      - Şablonlar: ./tebrikler/sablonlar/sablonlar.md
      - Test:
        - TestDeneme: ./test.md
theme:
  name: material
  palette:
    primary: blue
    accent: blue